spring:
  application:
    name: spot-intelligence

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:file:./data/spotdb;AUTO_SERVER=TRUE
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
gcp:
    api-key: ${GCP_API_KEY:}